# Generated by Django 2.2.12 on 2020-05-26 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('key', models.CharField(max_length=40, unique=True, verbose_name='Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth_exp_token', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expire_time', models.DateTimeField(default='2020-05-26 11:15:37.532566', verbose_name='expire_time')),
            ],
            options={
                'verbose_name': 'ExpiringToken',
                'verbose_name_plural': 'ExpiringTokens',
            },
        ),
    ]
